package dw.api.enums.quest;

public enum EQuestReward {
    COST_OF_LIVING,
    LOCAL_RENOWN_AND_CASH,
    POLITICAL_FAVOR,
    BIG_MONETARY_REWARD,
    FREE_PASS,
    WEAPONRY_AND_ARMOR,
    MAGIC_ITEMS,
    INFORMATION_OR_MAPS,
    SAFE_HAVEN,
    ALLIES_OR_FOLLOWERS,
    LAND_OR_TITLE,
    RELIGIOUS_BLESSING,
    DEBT_OWED,
    ARCANE_KNOWLEDGE,
    FREEDOM_OR_PARDON;
}
