package dw.api.enums.quest;

public enum EQuestTask {

    RESCUE,
    ACCOMPANY,
    EXPLORE,
    WIPE_OUT_WILD_TERRITORY,
    CHART_A_ROUTE,
    DEFEAT_ENEMY_FORCES,
    OBTAIN_ITEM_OR_TREASURE,
    INVESTIGATE_STRANGE_PHENOMENON,
    DELIVER,
    PROTECT,
    NEGOTIATE,
    SPY_OR_INFILTRATE,
    SABOTAGE,
    RETRIEVE_PERSON,
    ESTABLISH_OUTPOST,
    HUNT_CREATURE,
    SOLVE_MYSTERY,
    ESCORT_CARAVAN;



}
