package dw.api.enums.shared;

public enum ENames {

    // ARPAD - MALE
    AGOSTON(EGender.MALE, EEthnicity.ARPAD, "Agoston"),
    ARPAD(EGender.MALE, EEthnicity.ARPAD, "Arpad"),
    ATTILA(EGender.MALE, EEthnicity.ARPAD, "Attila"),
    BOGNAR(EGender.MALE, EEthnicity.ARPAD, "Bognar"),
    DENES(EGender.MALE, EEthnicity.ARPAD, "Denes"),
    EDMOND(EGender.MALE, EEthnicity.ARPAD, "Edmond"),
    ERNO(EGender.MALE, EEthnicity.ARPAD, "Erno"),
    ETELE(EGender.MALE, EEthnicity.ARPAD, "Etele"),
    FERDINAND(EGender.MALE, EEthnicity.ARPAD, "Ferdinand"),
    FLORIAN(EGender.MALE, EEthnicity.ARPAD, "Florian"),
    GEZA(EGender.MALE, EEthnicity.ARPAD, "Geza"),
    GYULA(EGender.MALE, EEthnicity.ARPAD, "Gyula"),
    HUGO(EGender.MALE, EEthnicity.ARPAD, "Hugo"),
    KARCSI(EGender.MALE, EEthnicity.ARPAD, "Karcsi"),
    KONRAD(EGender.MALE, EEthnicity.ARPAD, "Konrad"),
    LAZLO(EGender.MALE, EEthnicity.ARPAD, "Lazlo"),
    LUKAS(EGender.MALE, EEthnicity.ARPAD, "Lukas"),
    MARKO(EGender.MALE, EEthnicity.ARPAD, "Marko"),
    MIKLOS(EGender.MALE, EEthnicity.ARPAD, "Miklos"),
    PETI(EGender.MALE, EEthnicity.ARPAD, "Peti"),
    ROBI(EGender.MALE, EEthnicity.ARPAD, "Robi"),
    TAMAS(EGender.MALE, EEthnicity.ARPAD, "Tamas"),
    RONOLD(EGender.MALE, EEthnicity.ARPAD, "Ronold"),
    VIKTOR(EGender.MALE, EEthnicity.ARPAD, "Viktor"),
    ZOLTAN(EGender.MALE, EEthnicity.ARPAD, "Zoltan"),

    // ARPAD - FEMALE
    ABIGEL(EGender.FEMALE, EEthnicity.ARPAD, "Abigel"),
    ALIZ(EGender.FEMALE, EEthnicity.ARPAD, "Aliz"),
    AMALIA(EGender.FEMALE, EEthnicity.ARPAD, "Amalia"),
    ANDREA(EGender.FEMALE, EEthnicity.ARPAD, "Andrea"),
    ARANKA(EGender.FEMALE, EEthnicity.ARPAD, "Aranka"),
    CSILLA(EGender.FEMALE, EEthnicity.ARPAD, "Csilla"),
    EDIT(EGender.FEMALE, EEthnicity.ARPAD, "Edit"),
    ERZEBET(EGender.FEMALE, EEthnicity.ARPAD, "Erzebet"),
    GERTRUD(EGender.FEMALE, EEthnicity.ARPAD, "Gertrud"),
    GRETA(EGender.FEMALE, EEthnicity.ARPAD, "Greta"),
    IREN(EGender.FEMALE, EEthnicity.ARPAD, "Iren"),
    KAMILLA(EGender.FEMALE, EEthnicity.ARPAD, "Kamilla"),
    LARA(EGender.FEMALE, EEthnicity.ARPAD, "Lara"),
    LIA(EGender.FEMALE, EEthnicity.ARPAD, "Lia"),
    LUJZA(EGender.FEMALE, EEthnicity.ARPAD, "Lujza"),
    MATILD(EGender.FEMALE, EEthnicity.ARPAD, "Matild"),
    OLGA(EGender.FEMALE, EEthnicity.ARPAD, "Olga"),
    OTILIA(EGender.FEMALE, EEthnicity.ARPAD, "Otilia"),
    PANNA(EGender.FEMALE, EEthnicity.ARPAD, "Panna"),
    ROZA(EGender.FEMALE, EEthnicity.ARPAD, "Roza"),
    TEREZ(EGender.FEMALE, EEthnicity.ARPAD, "Terez"),
    TUNDA(EGender.FEMALE, EEthnicity.ARPAD, "Tunda"),
    VALERIA(EGender.FEMALE, EEthnicity.ARPAD, "Valeria"),
    VILMA(EGender.FEMALE, EEthnicity.ARPAD, "Vilma"),
    VIOLA(EGender.FEMALE, EEthnicity.ARPAD, "Viola"),

    // OLORU - MALE
    ADIBEMI(EGender.MALE, EEthnicity.OLORU, "Adibemi"),
    ABOYE(EGender.MALE, EEthnicity.OLORU, "Aboye"),
    ADEGOKE(EGender.MALE, EEthnicity.OLORU, "Adegoke"),
    AYOKUNLE(EGender.MALE, EEthnicity.OLORU, "Ayokunle"),
    BABAJIDE(EGender.MALE, EEthnicity.OLORU, "Babajide"),
    BABATUNDE(EGender.MALE, EEthnicity.OLORU, "Babatunde"),
    ENITAN(EGender.MALE, EEthnicity.OLORU, "Enitan"),
    FEMI(EGender.MALE, EEthnicity.OLORU, "Femi"),
    KAYIN(EGender.MALE, EEthnicity.OLORU, "Kayin"),
    KAYODE(EGender.MALE, EEthnicity.OLORU, "Kayode"),
    LANRE(EGender.MALE, EEthnicity.OLORU, "Lanre"),
    LEKAN(EGender.MALE, EEthnicity.OLORU, "Lekan"),
    MONGO(EGender.MALE, EEthnicity.OLORU, "Mongo"),
    NWACHUKWU(EGender.MALE, EEthnicity.OLORU, "Nwachukwu"),
    OBAN(EGender.MALE, EEthnicity.OLORU, "Oban"),
    OGUN(EGender.MALE, EEthnicity.OLORU, "Ogun"),
    OLUKAYODE(EGender.MALE, EEthnicity.OLORU, "Olukayode"),
    OLUWALAMNI(EGender.MALE, EEthnicity.OLORU, "Oluwalamni"),
    OLUWATOKE(EGender.MALE, EEthnicity.OLORU, "Oluwatoke"),
    ONIPEDE(EGender.MALE, EEthnicity.OLORU, "Onipede"),
    SIJUADE(EGender.MALE, EEthnicity.OLORU, "Sijuade"),
    TOBEN(EGender.MALE, EEthnicity.OLORU, "Toben"),
    UTIBA(EGender.MALE, EEthnicity.OLORU, "Utiba"),
    ZAKI(EGender.MALE, EEthnicity.OLORU, "Zaki"),
    ZOPUTAN(EGender.MALE, EEthnicity.OLORU, "Zoputan"),

    // OLORU - FEMALE
    ABENI(EGender.FEMALE, EEthnicity.OLORU, "Abeni"),
    ADE(EGender.FEMALE, EEthnicity.OLORU, "Ade"),
    ALABA(EGender.FEMALE, EEthnicity.OLORU, "Alaba"),
    BOLANLE(EGender.FEMALE, EEthnicity.OLORU, "Bolanle"),
    BOSADE(EGender.FEMALE, EEthnicity.OLORU, "Bosade"),
    DARAJA(EGender.FEMALE, EEthnicity.OLORU, "Daraja"),
    FARI(EGender.FEMALE, EEthnicity.OLORU, "Fari"),
    GBEMISOLA(EGender.FEMALE, EEthnicity.OLORU, "Gbemisola"),
    IFE(EGender.FEMALE, EEthnicity.OLORU, "Ife"),
    IGE(EGender.FEMALE, EEthnicity.OLORU, "Ige"),
    LEWA(EGender.FEMALE, EEthnicity.OLORU, "Lewa"),
    MOJISOLA(EGender.FEMALE, EEthnicity.OLORU, "Mojisola"),
    MONIFA(EGender.FEMALE, EEthnicity.OLORU, "Monifa"),
    OLUFEMI(EGender.FEMALE, EEthnicity.OLORU, "Olufemi"),
    OMOLARA(EGender.FEMALE, EEthnicity.OLORU, "Omolara"),
    ONI(EGender.FEMALE, EEthnicity.OLORU, "Oni"),
    ORISA(EGender.FEMALE, EEthnicity.OLORU, "Orisa"),
    OSA(EGender.FEMALE, EEthnicity.OLORU, "Osa"),
    RONKE(EGender.FEMALE, EEthnicity.OLORU, "Ronke"),
    SHANUM(EGender.FEMALE, EEthnicity.OLORU, "Shanum"),
    SIMISOLA(EGender.FEMALE, EEthnicity.OLORU, "Simisola"),
    TITLAYO(EGender.FEMALE, EEthnicity.OLORU, "Titlayo"),
    YEJIDE(EGender.FEMALE, EEthnicity.OLORU, "Yejide"),
    YEWANDE(EGender.FEMALE, EEthnicity.OLORU, "Yewande"),
    ZAUNA(EGender.FEMALE, EEthnicity.OLORU, "Zauna"),

    // VALKOINA - MALE
    AATAMI(EGender.MALE, EEthnicity.VALKOINA, "Aatami"),
    ARMAS(EGender.MALE, EEthnicity.VALKOINA, "Armas"),
    ARSI(EGender.MALE, EEthnicity.VALKOINA, "Arsi"),
    ARVI(EGender.MALE, EEthnicity.VALKOINA, "Arvi"),
    EETU(EGender.MALE, EEthnicity.VALKOINA, "Eetu"),
    HANNU(EGender.MALE, EEthnicity.VALKOINA, "Hannu"),
    HEIMO(EGender.MALE, EEthnicity.VALKOINA, "Heimo"),
    ILKKA(EGender.MALE, EEthnicity.VALKOINA, "Ilkka"),
    JORMA(EGender.MALE, EEthnicity.VALKOINA, "Jorma"),
    KAAPO(EGender.MALE, EEthnicity.VALKOINA, "Kaapo"),
    KAIN(EGender.MALE, EEthnicity.VALKOINA, "Kain"),
    KAUKO(EGender.MALE, EEthnicity.VALKOINA, "Kauko"),
    LARI(EGender.MALE, EEthnicity.VALKOINA, "Lari"),
    MANU(EGender.MALE, EEthnicity.VALKOINA, "Manu"),
    NUUTTI(EGender.MALE, EEthnicity.VALKOINA, "Nuutti"),
    PETRI(EGender.MALE, EEthnicity.VALKOINA, "Petri"),
    RAIMO(EGender.MALE, EEthnicity.VALKOINA, "Raimo"),
    REIMA(EGender.MALE, EEthnicity.VALKOINA, "Reima"),
    RISTO(EGender.MALE, EEthnicity.VALKOINA, "Risto"),
    SAKARI(EGender.MALE, EEthnicity.VALKOINA, "Sakari"),
    SAMPSA(EGender.MALE, EEthnicity.VALKOINA, "Sampsa"),
    SEPPO(EGender.MALE, EEthnicity.VALKOINA, "Seppo"),
    TAITO(EGender.MALE, EEthnicity.VALKOINA, "Taito"),
    TERHO(EGender.MALE, EEthnicity.VALKOINA, "Terho"),
    VILPPU(EGender.MALE, EEthnicity.VALKOINA, "Vilppu"),

    // VALKOINA - FEMALE
    AIJA(EGender.FEMALE, EEthnicity.VALKOINA, "Aija"),
    AINA(EGender.FEMALE, EEthnicity.VALKOINA, "Aina"),
    AINIKKI(EGender.FEMALE, EEthnicity.VALKOINA, "Ainikki"),
    HEINI(EGender.FEMALE, EEthnicity.VALKOINA, "Heini"),
    ILONA(EGender.FEMALE, EEthnicity.VALKOINA, "Ilona"),
    IRJA(EGender.FEMALE, EEthnicity.VALKOINA, "Irja"),
    JAANA(EGender.FEMALE, EEthnicity.VALKOINA, "Jaana"),
    KIRSI(EGender.FEMALE, EEthnicity.VALKOINA, "Kirsi"),
    MAIJA(EGender.FEMALE, EEthnicity.VALKOINA, "Maija"),
    MARITA(EGender.FEMALE, EEthnicity.VALKOINA, "Marita"),
    MIINA(EGender.FEMALE, EEthnicity.VALKOINA, "Miina"),
    MIMMI(EGender.FEMALE, EEthnicity.VALKOINA, "Mimmi"),
    MINJA(EGender.FEMALE, EEthnicity.VALKOINA, "Minja"),
    MIRA(EGender.FEMALE, EEthnicity.VALKOINA, "Mira"),
    NAEMI(EGender.FEMALE, EEthnicity.VALKOINA, "Naemi"),
    OUTI(EGender.FEMALE, EEthnicity.VALKOINA, "Outi"),
    PIRJO(EGender.FEMALE, EEthnicity.VALKOINA, "Pirjo"),
    PAIVIKKI(EGender.FEMALE, EEthnicity.VALKOINA, "Päivikki"),
    RIIKKA(EGender.FEMALE, EEthnicity.VALKOINA, "Riikka"),
    SAIMI(EGender.FEMALE, EEthnicity.VALKOINA, "Saimi"),
    SUOMA(EGender.FEMALE, EEthnicity.VALKOINA, "Suoma"),
    SUVI(EGender.FEMALE, EEthnicity.VALKOINA, "Suvi"),
    TUULA(EGender.FEMALE, EEthnicity.VALKOINA, "Tuula"),
    VELLAMO(EGender.FEMALE, EEthnicity.VALKOINA, "Vellamo"),
    VIRPI(EGender.FEMALE, EEthnicity.VALKOINA, "Virpi"),

    // TAMANARUGAN - MALE
    AGUS(EGender.MALE, EEthnicity.TAMANARUGAN, "Agus"),
    ADI(EGender.MALE, EEthnicity.TAMANARUGAN, "Adi"),
    AMAZIAH(EGender.MALE, EEthnicity.TAMANARUGAN, "Amaziah"),
    AYOKUNLE_INDO(EGender.MALE, EEthnicity.TAMANARUGAN, "Ayokunle"),
    ARY(EGender.MALE, EEthnicity.TAMANARUGAN, "Ary"),
    BAMBANG(EGender.MALE, EEthnicity.TAMANARUGAN, "Bambang"),
    BIMA(EGender.MALE, EEthnicity.TAMANARUGAN, "Bima"),
    BUDI(EGender.MALE, EEthnicity.TAMANARUGAN, "Budi"),
    DARMA(EGender.MALE, EEthnicity.TAMANARUGAN, "Darma"),
    DIAN(EGender.MALE, EEthnicity.TAMANARUGAN, "Dian"),
    ELI(EGender.MALE, EEthnicity.TAMANARUGAN, "Eli"),
    GUNARDI(EGender.MALE, EEthnicity.TAMANARUGAN, "Gunardi"),
    HARTONO(EGender.MALE, EEthnicity.TAMANARUGAN, "Hartono"),
    IRWAN(EGender.MALE, EEthnicity.TAMANARUGAN, "Irwan"),
    LAUWITA(EGender.MALE, EEthnicity.TAMANARUGAN, "Lauwita"),
    MANUSAMA(EGender.MALE, EEthnicity.TAMANARUGAN, "Manusama"),
    OKAN(EGender.MALE, EEthnicity.TAMANARUGAN, "Okan"),
    ONESIMUS(EGender.MALE, EEthnicity.TAMANARUGAN, "Onesimus"),
    SAMMIN(EGender.MALE, EEthnicity.TAMANARUGAN, "Sammin"),
    TAMEEM(EGender.MALE, EEthnicity.TAMANARUGAN, "Tameem"),
    TANAYA(EGender.MALE, EEthnicity.TAMANARUGAN, "Tanaya"),
    TIRTO(EGender.MALE, EEthnicity.TAMANARUGAN, "Tirto"),
    WIRYONO(EGender.MALE, EEthnicity.TAMANARUGAN, "Wiryono"),
    YANDI(EGender.MALE, EEthnicity.TAMANARUGAN, "Yandi"),
    ZEBULUN(EGender.MALE, EEthnicity.TAMANARUGAN, "Zebulun"),

    // TAMANARUGAN - FEMALE
    ADAH(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Adah"),
    BULAN(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Bulan"),
    CANDRAKUSUMA(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Candrakusuma"),
    DEVI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Devi"),
    HANJOJO(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Hanjojo"),
    IMAN(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Iman"),
    INTAN(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Intan"),
    LAKSMINI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Laksmini"),
    LESTARI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Lestari"),
    LIMIJANTO(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Limijanto"),
    MARAH(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Marah"),
    MEGAWATI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Megawati"),
    MELATI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Melati"),
    NADIYYA(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Nadiyya"),
    OPHRAH(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Ophrah"),
    RAMZA(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Ramza"),
    SAPPHIRAL(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Sapphiral"),
    SELAH(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Selah"),
    SUMINTEN(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Suminten"),
    TAMAR(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Tamar"),
    TANJAYA(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Tanjaya"),
    TJOKRO(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Tjokro"),
    TRI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Tri"),
    WANGI(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Wangi"),
    ZENZE(EGender.FEMALE, EEthnicity.TAMANARUGAN, "Zenze");


    private final EGender gender;

    private final EEthnicity ethnicity;

    private final String label;

    ENames(EGender gender, EEthnicity ethnicity, String label) {
        this.gender = gender;
        this.ethnicity = ethnicity;
        this.label = label;
    }

    public EGender getGender() {
        return gender;
    }

    public EEthnicity getEthnicity() {
        return ethnicity;
    }

    public String getLabel() {
        return label;
    }

}
