package dw.api.enums.npc;

public enum ENpcPersonality {
        LONER,
        ALIENATED,
        ANTISOCIAL,
        CRUEL,
        BELLIGERENT,
        BULLY,
        ANXIOUS,
        FEARFUL,
        COWARDLY,
        ENVIOUS,
        COVETOUS,
        GREEDY,
        ALOOF,
        HAUGHTY,
        ARROGANT,
        AWKWARD,
        SHY,
        SELF_LOATHING,
        ORDERLY,
        COMPULSIVE,
        CONTROLLING,
        CONFIDENT,
        IMPULSIVE,
        RECKLESS,
        KIND,
        GENEROUS,
        COMPASSIONATE,
        EASYGOING,
        RELAXED,
        PEACEFUL,
        CHEERFUL,
        HAPPY,
        OPTIMISTIC,
        ROLL_TWICE;
}
